import type { ComponentType } from "react";

import {
  AgendaTemplate,
  ArchitectureTemplate,
  BulletListTemplate,
  CardsTemplate,
  ClosingTemplate,
  ComparisonTemplate,
  CoverTemplate,
  DefinitionTemplate,
  GalleryTemplate,
  InfoBoxTemplate,
  KpiTemplate,
  MatrixTemplate,
  NumberedListTemplate,
  ObjectivesResultsTemplate,
  OverlayTemplate,
  ParagraphTemplate,
  ProblemSolutionTemplate,
  ProcessTemplate,
  QATemplate,
  QuoteTemplate,
  RoadmapTemplate,
  SectionTemplate,
  TableTemplate,
  TakeawaysTemplate,
  TimelineTemplate,
  VisualSplitTemplate,
  WorkflowTemplate,
} from "@/presentation/templates";
import type {
  SlideTemplateProps,
  SlideSemanticType,
} from "@/presentation/types";

export const templateRegistry: Record<
  SlideSemanticType,
  ComponentType<SlideTemplateProps>
> = {
  "cover.title": CoverTemplate,
  "section.agenda": AgendaTemplate,
  "section.transition": SectionTemplate,
  "content.paragraph": ParagraphTemplate,
  "content.definition": DefinitionTemplate,
  "content.definition_list": DefinitionTemplate,
  "content.multi_paragraph": ParagraphTemplate,
  "content.quote": QuoteTemplate,
  "content.info_box": InfoBoxTemplate,
  "list.bullets": BulletListTemplate,
  "list.numbered": NumberedListTemplate,
  "list.takeaways": TakeawaysTemplate,
  "list.pros_cons": ComparisonTemplate,
  "comparison.two_column": ComparisonTemplate,
  "comparison.before_after": ComparisonTemplate,
  "comparison.concepts": ComparisonTemplate,
  "comparison.solutions": ComparisonTemplate,
  "data.table": TableTemplate,
  "data.comparative_table": TableTemplate,
  "data.matrix": MatrixTemplate,
  "data.kpi": KpiTemplate,
  "data.cards": CardsTemplate,
  "visual.image_text": VisualSplitTemplate,
  "visual.overlay": OverlayTemplate,
  "visual.illustration": VisualSplitTemplate,
  "visual.gallery": GalleryTemplate,
  "diagram.timeline": TimelineTemplate,
  "diagram.process": ProcessTemplate,
  "diagram.workflow": WorkflowTemplate,
  "diagram.orgchart": WorkflowTemplate,
  "diagram.cause_effect": WorkflowTemplate,
  "business.problem_solution": ProblemSolutionTemplate,
  "business.objectives_results": ObjectivesResultsTemplate,
  "business.use_case": CardsTemplate,
  "business.roadmap": RoadmapTemplate,
  "business.architecture": ArchitectureTemplate,
  "business.product_feature": VisualSplitTemplate,
  "academic.definition": DefinitionTemplate,
  "academic.explanation": ParagraphTemplate,
  "academic.case_study": CardsTemplate,
  "academic.summary": TakeawaysTemplate,
  "academic.qa": QATemplate,
  "closure.conclusion": ClosingTemplate,
  "closure.thank_you": ClosingTemplate,
};
